"""Small, dependency-free WebVTT parser used before passing text to agents."""
from __future__ import annotations
import re
from dataclasses import dataclass

# Flexible regex that accepts times with or without hours (00:00:00.000 or 00:00.000)
TIMING_LINE = re.compile(r"(?P<start>(?:\d{1,2}:)?\d{1,2}:\d{2}\.\d{3})\s*-->\s*(?P<end>(?:\d{1,2}:)?\d{1,2}:\d{2}\.\d{3})")
TAG = re.compile(r"<[^>]+>")

@dataclass(frozen=True)
class Caption:
    start: str
    end: str
    text: str

def timestamp_seconds(timestamp: str) -> float:
    parts = timestamp.split(":")
    if len(parts) == 3:
        hours, minutes, seconds = parts
    elif len(parts) == 2:
        hours = "0"
        minutes, seconds = parts
    else:
        hours = "0"
        minutes = "0"
        seconds = parts[0]
        
    whole_seconds, milliseconds = seconds.split(".")
    return int(hours) * 3600 + int(minutes) * 60 + int(whole_seconds) + int(milliseconds) / 1000

def process_caption_text(raw_text: str) -> str:
    """Clean up and normalize the mess generated by the LLM."""
    # 1. Convert <v Name> to Name:
    text = re.sub(r"<v\s+([^>]+)>", r"\1: ", raw_text)

    # 2. Convert [Name]: to Name: (for cases like [SPEAKER_SAM]:)
    text = re.sub(r"\[([^\]]+)\]:\s*", r"\1: ", text)

    # 3. Remove audio/effect descriptions (e.g. [TRAFFIC BUZZ])
    text = re.sub(r"\[.*?\]", "", text)

    # 4. Remove the "SPEAKER_" string if the LLM was repetitive
    text = re.sub(r"SPEAKER_", "", text)

    # 5. Remove native VTT tags (like </v>)
    text = TAG.sub("", text)

    # 6. Clean up double spaces left by the removals above
    return re.sub(r"\s+", " ", text).strip()

def parse_vtt(raw_vtt: str) -> list[Caption]:
    """Extract time-stamped spoken captions, rejecting malformed uploads."""
    normalized = raw_vtt.lstrip("\ufeff").replace("\r\n", "\n").replace("\r", "\n")
    
    captions: list[Caption] = []
    lines = normalized.split("\n")
    
    current_start = None
    current_end = None
    current_text = []

    for line in lines:
        line = line.strip()
        
        # Silently ignore headers made up by the LLM
        if line.startswith("WEBVTT") or line.startswith("Kind:") or line.startswith("Language:") or line.startswith("Note Date:"):
            continue

        if not line:
            # End of a speech block
            if current_start and current_text:
                raw_text = " ".join(current_text)
                clean_text = process_caption_text(raw_text)
                if clean_text:
                    captions.append(Caption(start=current_start, end=current_end, text=clean_text))
            
            current_start = None
            current_end = None
            current_text = []
            continue

        match = TIMING_LINE.search(line)
        if match:
            current_start = match.group("start")
            current_end = match.group("end")
        elif current_start:
            # Once we have the timing, the following lines are dialogue
            current_text.append(line)

    # Process the last block in case the LLM didn't leave a blank line at the end
    if current_start and current_text:
        raw_text = " ".join(current_text)
        clean_text = process_caption_text(raw_text)
        if clean_text:
            captions.append(Caption(start=current_start, end=current_end, text=clean_text))

    if not captions:
        print("[WARNING] No readable dialogue found. Returning a safe fallback file.")
        return [Caption(start="00:00:00.000", end="00:00:00.000", text="No readable dialogue found.")]
        
    return captions

def transcript_from_captions(captions: list[Caption]) -> str:
    return "\n".join(f"[{cue.start}–{cue.end}] {cue.text}" for cue in captions)

def duration_seconds(captions: list[Caption]) -> int:
    """Return the elapsed duration from the first cue start to the last cue end."""
    if len(captions) == 1 and captions[0].text == "No readable dialogue found.":
        return 0
    return max(0, round(timestamp_seconds(captions[-1].end) - timestamp_seconds(captions[0].start)))

def participants_from_captions(captions: list[Caption]) -> list[str]:
    """Get unique speaker names in first-appearance order from caption text."""
    names: list[str] = []
    for caption in captions:
        possible_name, separator, _ = caption.text.partition(":")
        name = possible_name.strip()
        if separator and name and name not in names:
            names.append(name)
    return names

def format_timestamp(seconds: float) -> str:
    """Format elapsed seconds for display: M:SS, or H:MM:SS past one hour."""
    total = round(seconds)
    hours, remainder = divmod(total, 3600)
    minutes, secs = divmod(remainder, 60)
    if hours:
        return f"{hours}:{minutes:02d}:{secs:02d}"
    return f"{minutes}:{secs:02d}"
